name = "player"
type = "blueprint"
[components]
sprite_component = {color = [1,1,0,1]}
script_component = ["player_move_script"]
dynamic_body = {position = [1,0], collision_callback = "check_health_callback"}
stats_component = {}
